### ISSUE TITLE
Add instructions on how to build the debian package

### ISSUE THREAD

**Issue by thedrow** [troglobit/smcroute#101]
The README should contain the instructions for building a Debian package for those of us who are not using Debian unstable (or for people to install newer versions).
Usually the Makefile contains a `deb` target, but that's currently not the case.
We could document the manual process or automate it.

**Comment by troglobit** [comment]
I'm sorry, but I don't agree with that at all.  This is the upstream SMCRoute project and I believe it should remain distribution agnostic.  Sure, for other projects I maintain I keep native Debian packaging but that is mostly because I'm not a Debian Developer (yet).

We are (still) working on getting the latest version of SMCRoute into Debian and when it arrives in unstable it is a straight forward task to backport it to older releases or even other distributions, e.g. Ubuntu.

I'm closing this issue as wont-fix.
