### ISSUE TITLE
i want to install smcroute by homebrew

### ISSUE THREAD

**Issue by tarpik1004** [troglobit/smcroute#177]
i want to install smcroute by homebrew

could you add homebrew package?

**Comment by troglobit** [comment]
You mean for macOS?  Does the Darwin kernel support multicast routing now?  

Regardless, this is the upstream SMCRoute project.  We don't have the possibility to support all different packaging formats, CPU architectures, operating systems, etc.  This is usually handled downstream from us, e.g. on Linux, Debian/RedHat/Suse/Arch provide packaging for their respective formats.  On BSD UNIX systems it's usually available in the ports collection or their corresponding pkg formats.

Tagging this wont-fix because any packaging is not core to the project.
