### ISSUE TITLE
Problem with leaving group (v 2.4.4 Debian 11)

### ISSUE THREAD

**Issue by rsti301** [troglobit/smcroute#191]
Hi, 
I'm using smcrouted as a multicast client and I have sometimes problem with leaving a group, for example after my LAN router restart or during some network problems. After that I'm ending with local multicast addresses configured but no subscriptions in smcrouted. I cannot leave and delete the mcast interface and the only thing that helps in this case is system restart.
Do you know any other way I could delete the multicast address? It seems that even when join returns an error - smcrouted is creating a multicast address in system. Here are some sample logs:

`2022-10-31 13:39:25.465:[0x1842e0dbead] smcroutectl join  eth0 230.0.20.83`
`2022-10-31 13:39:25.474:[0x1842e0dbead] smcroutectl: failed join (*,230.0.20.83) on eth0, no interface address.`
`2022-10-31 13:39:46.866:[0x1842e0e1971] smcroutectl leave  eth0 230.0.19.83`
`2022-10-31 13:39:46.873:[0x1842e0e1971] smcroutectl: failed leave (*,230.0.19.83), not a member`

But mcast ip still exists in the output of ip maddr command and it seems that kernel in that case sends periodic igmp queries.

Maybe this behaviour is fixed in 2.5 version? Can you confirm that ?

**Comment by troglobit** [comment]
Hi, v2.4.4 is over 3½ years old.  I have no means of supporting that old software, in particular since there have been many releases since.  If you are using packaged version from Debian you should report the bug to them, not the upstream project (us).

Now, to answer your question -- the v2.5.x series was a complete rewrite of some subsystems in SMCRoute, join/leave was one of them.  I cannot confirm if the changes include fixes to your particular problem, so I suggest you try a later version, it's not hard to compile from the latest released tarball.
