### ISSUE TITLE
Routing problems with Wake On LAN on OpenWRT

### ISSUE THREAD

**Issue by crocket** [troglobit/smcroute#53]
```
mgroup from wlan0 group 224.0.2.1
mroute from wlan0 group 224.0.2.1 to br-lan
```

```
iptables -t mangle -A OUTPUT -d 224.0.2.1 -j TTL --ttl-set 64
```

I can detect Wake-On-Lan UDP multicast packets to 224.0.2.1 on wlan0 with wireshark.
But, it is not detected on br-lan.

openwrt 15.05.1

**Comment by troglobit** [comment]
Curious, so your `wlan0` interface is not part of the bridge `br-lan`?  If it was up to me I'd just bridge the LAN ports and the WiFi interface, much easier setup.

Now, I'm not aware of later versions (>= 2.0) of SMCRoute being available in OpenWRT,
what version of SMCRoute are you using?  

Can you see that SMCroute actually sets the route in the kernel? This is visible in `/proc/net/ip_mr_cache`,
or using the iproute2 command: `ip mroute`.  If it's not visible, try adding `source <SENDER_IP>` to the `mroute` rule in your `/etc/smcroute.conf`.  If it's still not working after that, then I guess the firewall mangling of the TTL doesn't bite.

**Comment by crocket** [comment]
`wlan0` is a DHCP client which has a statically leased DHCP IP address 192.168.0.2.
`br-lan` is a DHCP server that has a static IP address 192.168.1.1.

The router, `192.168.0.1` for `wlan0` has a route `224.0.2.1 via 192.168.0.2` which I manually added. Since the router at 192.168.0.1 doesn't have a multicast routing daemon and openwrt, I had to add an IPv4 route to it.

```
# smcroute -v
SMCRoute version 2.0.0 build 160131
# ip mroute
(192.168.0.2, 224.0.2.1)         Iif: wlan0      Oifs: br-lan
```

Also, the firewall rule is triggered whenever I send a multicast WoL UDP packet to 224.0.2.1 from 192.168.0.11 which is the IP address of my android smartphone.

**Comment by troglobit** [comment]
I see, well then it's obvious you need to route the multicast.  The only problem is that WOL is usually scoped to the LAN, i.e. hard-coded TTL=1 from the sender.

The SMCRoute version looks OK, and so does the multicast route.

You should see inbound multicast for 224.0.2.1 on wlan0 with tcpdump.  With the `-vvv` switch to tcpdump you should see the (mangled) TTL value.  If it's set to 1 then the kernel will drop it and there's not much to do besides tinker around with the iptables mangle rule, which you've already found, to see if you can fix the scoping.

Sorry if I cannot be of more help.

**Comment by crocket** [comment]
On my openwrt router, 192.168.1.1 and 192.168.0.2
```
~# tcpdump -i any -n -vvv port 9
tcpdump: listening on any, link-type LINUX_SLL (Linux cooked), capture size 65535 bytes
23:42:31.526499 IP (tos 0x0, ttl 1, id 0, offset 0, flags [DF], proto UDP (17), length 130)
    192.168.0.10.40048 > 224.0.2.1.9: [udp sum ok] UDP, length 102
23:42:31.526697 IP (tos 0x0, ttl 1, id 0, offset 0, flags [DF], proto UDP (17), length 130)
    192.168.0.10.45482 > 224.0.2.1.9: [udp sum ok] UDP, length 102
23:42:31.526817 IP (tos 0x0, ttl 1, id 0, offset 0, flags [DF], proto UDP (17), length 130)
    192.168.0.10.60109 > 224.0.2.1.9: [udp sum ok] UDP, length 102
```

**Comment by troglobit** [comment]
Yup, the TTL is 1, and also the reason for the multicast not being routed.  

Unfortunately I'm not fluent in iptables-speak, so I cannot help you with the syntax for getting the
mangling to work. Maybe you need to do the mangling on INPUT?  Dunno ...

**Comment by troglobit** [comment]
Here's some info on iptables that might be of use, mentions using PREROUTING
https://www.netfilter.org/documentation/HOWTO/netfilter-extensions-HOWTO-4.html

    iptables -t mangle -A PREROUTING -i wlan0 -j TTL --ttl-inc 1

**Comment by crocket** [comment]
After executing `iptables -t mangle -A PREROUTING -i wlan0 -d 224.0.2.1 -j TTL --tlc-inc 1`, I could wake up my server `192.168.1.2` with a multicast WoL packet from `192.168.0.10`.

192.168.0.10 -> 192.168.0.1(router1) -> 192.168.0.2(router2 wlan0) -> 192.168.1.1(router2 br-lan) -> 192.168.1.2(my server)

This hack feels nasty because I manually added an IPv4 route `224.0.2.1 via 192.168.0.2` to router1 and an iptables rule for mangling TTL to router2.

Can I at least avoid adding the route `224.0.2.1 via 192.168.0.2`?

**Comment by crocket** [comment]
Is there a way to avoid making an iptables rule for increasing TTL values of multicast packets generated by my android app `Wake On Lan`?

**Comment by troglobit** [comment]
Great that you got it working!

The great thing about multicast is that you can have multiple receivers. So you shouldn't really need to have the separate route from router1 --> router2.  It should be sufficient to have the `mgroup ...` rule on router2 so that it joins group 224.0.2.1 (using IGMP) on that subnet.

The default TTL value for both multicast and broadcast is 1. In most cases when there's a problem with too low TTL, I advise ppl to increase it at the sender.  The mangling hack is mostly for those odd cases when you have no control over the sender, which I guess in this case you don't?  I suspect the *Wake On Lan* app does not have a setting to adjust the TTL, since WOL messages are usually for the *same* LAN.

(Sorry for the late answer, had to get some sleep here, CET)

**Comment by troglobit** [comment]
Ah, you edited your post(s) ... I'll make a followup.

The reason why disabling disabling multicast (IGMP) snooping on your bridge makes it work is that the end-node (192.168.1.2) doesn't subscribe to the multicast group you are forwarding from the OpenWRT router.  

1. Try re-enabling snooping again
2. Check that the end node receives IGMP queries from 192.168.1.1 periodically
3. Try, e.g., [mcjoin](https://github.com/troglobit/mcjoin) on the server to send join for these queries
4. Profit

I do agree with your sentiment that one shouldn't disable snooping, and yes, I should probably update the FAQ to mention my having to disable snooping on the bridge in my setup was due to a bug in the bridge code at the time.

As far as my experience goes, OSPF is for routing unicast, unless you meant MOSPF.

**Comment by troglobit** [comment]
Ah, good point.  Must remember to turn my brain *on* in the morning ;)

There is this one thing you could do on the OpenWRT router.  Dunno what kernel version you have, but in later versions there is a bridge setting, somewhere in /sys, that can enable a multicast "router port".  I.e., send all multicast this way.  But that would forward *all* multicast to the server ... so maybe "bridge mdb add ..." would be more to your liking?

**Syntax:**

    bridge mdb { add | del } dev DEV port PORT grp GROUP [permanent | temp] [vid VID]

**Example:**

    bridge mdb add dev br0 port eth1 grp 224.0.2.1 permanent

Dunno what  bridge ports you have in your br-lan bridge, but that's what should go into the `port PORT` argument to bridge mdb at least.  This would add a static entry on layer-2 to forward multicast for the given group.

**Comment by crocket** [comment]
The latest stable version of OpenWrt comes with

```
# uname -r
3.18.23
```

I haven't found `bridge` command yet on OpenWrt.

**Comment by troglobit** [comment]
So you got it working, that's great news! :smiley:  :+1: 

Very often there are issues at bootup that needs to be tweaked. I guess in your case the `br-lan` bridge may not be up yet.  Try starting `smcroute -d` in `/etc/rc.local`, or maybe even fork off a process from rc.local that starts it later.  Unfortunately I've not added any "delayed start" to SMCRoute, so you'll need workarounds, or an init that can handle dependencys, so that SMCRoute isn't started until all interfaces have been created and are up.

Guess we can close this issue now, after all it wasn't a problem with SMCRoute :-)

**Comment by crocket** [comment]
Yeah, thanks for helping with my issue.
I'll look for a way to make smcroute start lately.

**Comment by troglobit** [comment]
I've added a ‘-t SEC‘ startup delay to the next SMCRoute release, on GIT master now. It won't help you now, but at least your problems created a new feature for future users 😊

Good Luck mate!

**Comment by crocket** [comment]
```
/etc/rc.local:
bridge mdb add dev br-lan port eth0.1 grp 239.0.0.0 permanent
sh -c 'sleep 60; smcroute -d' &
exit 0
```

Since `bridge mdb add dev br-lan port eth0.1 grp 239.0.0.0 permanent` works but `smcroute -d` doesn't work in `/etc/rc.local`, `br-lan` is probably already present when `/etc/rc.local` is executed.

**Comment by troglobit** [comment]
Have you tried ‘-L debug‘?

**Comment by crocket** [comment]
I created new issues. Let's discuss there.
