### ISSUE TITLE
smcroute -n does not imply -d (daemon), fails silently

### ISSUE THREAD

**Issue by crocket** [troglobit/smcroute#56]
In some other daemons, foreground options imply running daemon.
I assumed the same convention for smcroute, and I wasted time.

I think smcroute should either make `-n` imply `-d` or explicitly state that `-n` doesn't imply `-d`.

**Comment by troglobit** [comment]
This has always bugged me too, ever since I took over maintainership from Carsten.

Most other daemons are daemons by default, not a combined daeon and client with the same name.
If there is a daemon its usually called `smcrouted` and the client is called something like `smcroutectl`

I've been pondering changing in this, but it could potentially make many other users angry and to
avoid that one could implement it such that keeping a `smcroute` symlink to either the client or
the daemon where you'd have to supply `-d` to be redirected to start `smcrouted`.

In the meantime, maybe if I add a warning to `-n` that could print to `stderr` if `-d` is not given as well?
Because `-n` without `-d` would have no effect.

**Comment by crocket** [comment]
It is a good idea to give a warning.

**Comment by troglobit** [comment]
Maybe it's time to do that refactor and split into a daemon and a client ... then it would be possible to
opt to build without the client (only .conf file) and save some space.  (Some embedded systems are
*really* tight on space, even in this day and age ...)

Leaving this issue open, maybe someone else would like to chime in on such a change,
like @bombadil perhaps?

**Comment by bombadil** [comment]
I think it's a good idea to separate daemon and client code from each other. Please just avoid duplicating code because of this.

**Comment by troglobit** [comment]
@bombadil Thank you for the support!  And, of course.

I was thinking of making it a multicall binary.
