### ISSUE TITLE
Syslog: Signaling Dropped

### ISSUE THREAD

**Issue by antoniovalenzuela** [troglobit/smcroute#79]
Openwrt 12.09
SMCROUTE Version 0.92, Build 130314

Client
--------
Syslog
**Debu: 28 byte IGMP signaling dropped**

echo "0" > /sys/devices/virtual/net/br-lan/bridge/multicast_snooping
echo "0" > /proc/sys/net/ipv4/icmp_echo_ignore_broadcasts

smcroute -j tun0 239.255.255.250
smcroute -a tun0 10.0.1.6 239.255.255.250 br-lan

No firewall
OpenVPN tun0
br-lan   lan0/wlan0

ip -s mroute
(10.0.1.6, 239.255.255.250)      Iif: tun0       Oifs: br-lan

Server
---------
 ip -s mroute
(192.168.80.5, 239.255.255.250)  Iif: wlan0      Oifs: tun0
  181 packets, 20552 bytes

**Comment by troglobit** [comment]
Not sure what your question is here ... just a lot of stats and settings ... no actual question posed?

The debug message "28 byte IGMP signaling dropped" can be safely ignored, since SMCRoute (in your version) does not care at all about IGMP.  It is merely printed as a debug message to the log to notify the user (admittedly somewhat confusingly) that the kernel socket has received an IGMP message.

If you have a question, please post it in a follow-up message below.  There are however a few things I'd like to point out first:

1. This is a VERY old version of SMCRoute, that we cannot support
2. Bug for software packaged as part of a distribution should be reported to the distribution first

If you don't have a question, please close this issue, or I will within a months time.

**Comment by antoniovalenzuela** [comment]
If, it is due to the message "signaling dropped". I thought it was a restriction.

Thanks for the clarification.
