### ISSUE TITLE
Source IGMP from server VIF/secondary IPs

### ISSUE THREAD

**Issue by ameyaptk** [troglobit/smcroute#88]
Hi,

I'm running smcrouted from a RHEL server and am planning to source the joins from a secondary IP (also known as virtual interface). The IP in this case is 10.10.2.15. Here is the ifconfig-

enp94s0f0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.10.1.162  netmask 255.255.255.224  broadcast 10.10.1.191
        inet6 fe80::20f:53ff:fe20:f970  prefixlen 64  scopeid 0x20<link>
        ether 00:0f:53:20:f9:70  txqueuelen 1000  (Ethernet)
        RX packets 2078359238  bytes 2388686018879 (2.1 TiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 239474  bytes 17465230 (16.6 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device interrupt 47

enp94s0f0:1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.10.2.15  netmask 255.255.255.254  broadcast 255.255.255.255
        ether 00:0f:53:20:f9:70  txqueuelen 1000  (Ethernet)
        device interrupt 47

I tried multiple formats of smcrouted.conf

mgroup from enp94s0f0:1 group 224.0.31.70
mgroup from 'enp94s0f0:1' group 224.0.31.70
mgroup from enp94s0f0\:0 group 224.0.31.70

But none of them seem to work. How can we source igmp from a secondary IP for an interface?

**Comment by troglobit** [comment]
The syntax that should work, with `-N` as argument to `smcrouted`, is

```
phyint enp94s0f0:1 enable
mgroup from enp94s0f0:1 group 224.0.31.70
```

I did some testing today with a similar setup, using a virtual interface like you, and with some trace debug messages I could clearly see that `mcgroup.c:mcgroup_join_leave_ipv4()` does indeed call `setsockopt()` with a `struct ip_mreq` that has the correct multicast group and interface IP address.
However, the kernel doesn't seem to care but instead sends out an IGMP join on the wire with the primary IP of the base interface. So I can only conclude that virtual interfaces are not supported for this particular use-case.

Also, SMCRoute currently only supports configuring the `phyint` from the interface name. A possible solution to your problem could be to add support for specifying the interface using the address instead. Similar to how the mrouted and pimd config works.  E.g. `phyint 10.10.2.15 enable`, but that would likely also require using `ip addr add` to add more addresses to an interface instead of the archaic virtual interface thingy ... and even so, that's no guarantee the kernel would use that address as the source IP in the IGMP join message on the wire.  You see, the IGMP join that SMCRoute does for you with the `mgroup` command is a local join, i.e. "this process wants this multicast group, please kernel could you forward that to me" ... and if the multicast is locally available (provided on the same system but from another process) we would get it immediately.

**Comment by ameyaptk** [comment]
Got it. Thanks! You're right, the kernel for some reason seems to not consider the secondary IP address and is always sourcing the packet from the primary IP.

**Comment by troglobit** [comment]
So ... maybe we can close this issue with SMCRoute then?

**Comment by ameyaptk** [comment]
Yes please. Thanks!
