### ISSUE TITLE
smcroute and s,g joins ... am I failing?

### ISSUE THREAD

**Issue by oriziena** [troglobit/smcroute#95]
hi all,

am I failing or does smcroute NOT support joining of igmpv3 (s,g) based joins?

current config /etc/smcroute.conf
mgroup from eno52.200 source 198.18.73.251 group 232.27.72.64
mgroup from eno52.200 source 198.18.73.251 group 232.27.72.67

tcpdump:
11:47:28.856822  In PFE proto 2 (ipv4): (tos 0xc0, ttl   1, id 0, offset 0, flags [DF], proto: IGMP (2), length: 56, optlength: 4 ( RA )) 192.168.123.1 > 224.0.0.22: igmp v3 report, 3 group record(s) [gaddr 232.27.72.67 is_ex, 0 source(s)] [gaddr 232.27.72.64 is_ex, 0 source(s)] [gaddr 224.0.0.252 is_ex, 0 source(s)]

why is the source not added in the membership report?

thx and sorry if this is a dump question :(

greetings
ori

update:
version: SMCRoute version 2.0.0 build 150506
linux: Ubuntu 16.04.4 LTS
kernel:  4.13.0-45-generic

**Comment by troglobit** [comment]
No you're correct, SSM group join support was initially added in v2.2.0.  The currently released SMCRoute version is v2.4.1, where SSM group join support has long since been folded into the standard 'group' .conf file setting, as well as in inte command line client.

See #94 for status of the upcoming update of SMCRoute in Debian/Ubuntu.

**Comment by troglobit** [comment]
Since this is a problem with the downstream packaged (older) version of SMCRoute, I'm closing this issue without further action.

**Comment by oriziena** [comment]
manual installation of 2.4.1 fixed the issue... thx
