### ISSUE TITLE
Cannot route between 2 subnets

### ISSUE THREAD

**Issue by shotahino** [troglobit/smcroute#99]
Apology in advance in case this does not make sense or too generic.

### Setup
I have a custom linux computer acting as a router and wifi access point. 2 clients are wirelessly connected to it, but they are on _different_ subnets. The linux runs DHCP server and hands out the IP addresses to them.

I want to bridge multicast traffic between them, and I am unable to do so using `smcrouted` (or any other way).

I've built and installed version `2.4.1`. My linux kernel is `v3.14.0`. Architecture is `armhf`.

### Details
`smcroute.conf`: Note `224.0.0.x` is actually some valid group address on my linux.
```
phyint yyyy enable ttl-threshold 10
phyint zzzz enable ttl-threshold 10

mgroup from yyyy group 224.0.0.x
mgroup from zzzz group 224.0.0.x

mroute from yyyy group 224.0.0.x to zzzz
mroute from zzzz group 224.0.0.x to yyyy
```

Both `yyyy` and `zzzz` interfaces have `MULTICAST` flag in the output of `ifconfig`.
`yyyy` is a bridge interface, but I don't think it matters right? 

I also have firewall on my linux to modify the TTL and set it to 64.

I also confirmed that IGMP is supported on my linux.
```
// protocol family 2 is IGMP
Aug 24 05:02:33 local2.info kernel: [    0.395445] NET: Registered protocol family 2
```

### Problem
Let's say we have clients A and B, they are on different subnets. 
* Client A sends multicast traffic to `224.0.0.x`. 
* I have confirmed from `tcpdump -i yyyy` that the multicast packets arrive at my linux from client A. 
* However, I do not think they are forwarded to the subnet that client B is on. 
* `smcroutectl show routes` show that there were 0 packets that got forwarded from `yyyy` to `zzzz`

Any piece of tips, things I should try is greatly appreciated
Edit: Is there any way to confirm that clients A and B have joined the group `224.0.0.x`?  and how will the linux know about it?

### Dummy question
Some online posts suggested that we add route by`ip route add 224.0.0.0/4 dev yyyy` while some other posts suggest that this command is for unicast routing.  So, I am confused which one is correct.

My understanding is that multicast routing is totally different and linux needs special software such as `smcroute` to handle multicast routing. So, it feels strange if we also need to use `ip route` command.

**Comment by troglobit** [comment]
It matters if the destination interface is a bridge.  The bridge has multicast filtering enabled by default, so either the end devices need to send a "join" for the required group, or you need to disable filtering, like this:

    echo 0 > /sys/devices/virtual/net/yyybridge/multicast_snooping

You can verify the TTL mangling with tcpdump on the bridge.

**Comment by shotahino** [comment]
@troglobit Thank you for the info. 

I confirmed that TTL mangling is working by enabling packet tracing in `iptables`
But I observed something strange. 

- My packet tracing in `iptables` shows that the below multicast packet (address `239.255.255.250`) has TTL of 1. 
- However, the log from `smcroute` indicates that it was trying to route to different subnets.

Since this is not my desired multicast packet, I do not have any rule defined for this group in `smcroute.conf`. It is not causing a problem, but I like to understand why this is happening. 

I am hoping that understanding this might explain why me desired multicast packet is not routed by `smcroute`.

I am using `v2.4.1`. 

```
Aug 25 02:33:31 kernel: TRACE: nat:PREROUTING:rule:10 IN=zzzz OUT= MAC=qqqqq SRC=192.168.12.21 DST=239.255.255.250 LEN=203 TOS=0x00 PREC=0x00 TTL=1 ID=41685 PROTO=UDP SPT=62621 DPT=1900 LEN=183
```

```
Aug 25 02:33:31 smcroute[7403]: New multicast data from 192.168.12.21 to group 239.255.255.250 on VIF 24
Aug 25 02:33:31 smcroute[7403]: Multicast from 192.168.12.21, group 239.255.255.250, on zzzz does not match any (*,G) rule
```

**Comment by troglobit** [comment]
I should have written this in my initial reply; 224.0.0.x are reserved for link-local control traffic.  It is not supposed to be routed.  We get questions about this from time to time, in particular about 224.0.0.251 (mDNS), but this is the first time someone wants to route IGMP v3. 

Also, the bridge has special handling for 224.0.0.x which prevents anyone from joining groups in that range (since they are reserved).

The `ttl-threshold` setting is a scoping mechanism for mulitcast, it is only useful if you have multiple sources of multicast with different TTLs and you want to set up routing boundaries.  Most use-cases should leave this to the default setting, which is 2.  For a router to forward an IP frame it starts by decrementing the TTL, if the resulting TTL is > 0 the packet is forwarded (unless scoping on the outbound interface is in place, above).

Exactly what are you trying to achieve?   You stated above that you want to "bridge multicast" between two different subnets.  If this is for mDNS, so to allow clients on the two subnets to see each other, you may want to reconsider since an mDNS A record can return a 169.254.x.y (link-local) address which also cannot be routed.  However, if your clients wants to share movies, or similar, using a non-224.0.0.x group address, then SMCRoute can help you.

I'm sorry if I come off harshly in my reply, but trying to fight standards like this is sort of doomed for failure. If I was in your shoes I'd try to reconsider my approach; maybe try a layer-2 tunnel, like VXLAN, between the clients instead.

**Comment by shotahino** [comment]
@troglobit Thank you very much. I wanted mDNS traffic to travel between 2 subnets so clients on different subnets can see each other. It sounds like this is against standard and I am set up for a failure. I will look into VXLAN. Thank you very much for your help.

**Comment by troglobit** [comment]
@shotahino No problem, I wish you the best of luck! :)

**Comment by gdavila** [comment]
Hello, 

I just started to use smcroute. I have a similar issue but with no bridge interfaces.

```
phyint ens224 enable
mgroup from ens192 group 239.100.0.5 source 10.254.245.140
mroute from ens192 group 239.100.0.5 source 10.254.245.140 to ens224

```
Using wireshark I can see the multicast traffic over ens192 but no data over ens224 iface.

```
:~$ sudo smcroutectl show routes
ROUTE (S,G)                        INBOUND             PACKETS      BYTES  OUTBOUND 
(10.254.245.140, 239.100.0.5)      ens192                   0          0  ens224
```
I'm using Ubuntu 18.04 running as VM with WMWare.

Any clue about what might be happening?

**Comment by gdavila** [comment]
Solved.

The rp_filters were missconfigured. With conf it works.

```
net.ipv4.conf.ens192.rp_filter = 0
net.ipv4.conf.ens224.rp_filter = 0
```

**Comment by troglobit** [comment]
@gdavila For future reference, it is always better to open a new issue and then reference an existing one.  In particular when the existing one is already closed.  Nevertheless, glad to hear you found the root cause of your issue :)
